main:
  image:
    repository: ghcr.io/dramatikman/mlhl-gradwork-server
    tag: latest

  command: ["gwserver"]
  args: ["start", "api"]

  ingress:
    hosts:
      - host: gw.sergeypavlov.dev
        paths:
          - path: /api
            pathType: Prefix
    tls:
    - secretName: tls.sergeypavlov.dev
      hosts:
        - gw.sergeypavlov.dev

  envVars:
    - secret: gwserver-main

  initContainers:
    - name: init
      command: ["gwserver"]
      args: ["init", "all"]

  sidecars:
    - name: workers
      command: ["gwserver"]
      args: ["start", "workers", "--count=2"]

  persistentVolumes:
    - name: gwserver-model
      mountPath: /tmp/model
      volumeClaim:
        size: 100Mi

postgresql:
  fullNameOverride: gwserver-postgresql
  auth:
    postgresPassword: postgres
    username: postgres
    password: postgres
    database: postgres
  primary:
    service:
      type: NodePort
    persistence:
      size: 1Gi

rabbitmq:
  fullNameOverride: gwserver-rabbitmq
  auth:
    username: rabbitmq
    password: rabbitmq
    erlangCookie: erlangCookie
  persistence:
    enabled: false
