services:

  gwserver:
    build:
      context: .
    env_file:
      - ./secret.env
    ports:
      - "8000:8000"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  broker:
    image: rabbitmq:management
