services:

  api:
    build:
      context: .
    command: ["gwserver", "start", "api"]
    env_file:
      - ./secret.env
    ports:
      - "8000:8000"

  workers:
    build:
      context: .
    command: ["gwserver", "start", "workers"]
    env_file:
      - ./secret.env

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  broker:
    image: rabbitmq:management
