services:

  api:
    image: ghcr.io/dramatikman/mlhl-gradwork-server:latest
    command: ["gwserver", "start", "api"]
    env_file:
      - ./secret.env
    ports:
      - "8080:8080"
    depends_on:
      init:
          condition: service_completed_successfully

  init:
    image: ghcr.io/dramatikman/mlhl-gradwork-server:latest
    command: ["gwserver", "init", "all"]
    env_file:
      - ./secret.env
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - model:/app/model

  workers:
    image: ghcr.io/dramatikman/mlhl-gradwork-server:latest
    command: ["gwserver", "start", "workers"]
    env_file:
      - ./secret.env
    depends_on:
      init:
          condition: service_completed_successfully
      broker:
        condition: service_started
    volumes:
      - model:/app/model

  postgres:
    image: postgres:alpine
    env_file:
      - ./secret.env

  broker:
    image: rabbitmq:management
    depends_on:
      init:
          condition: service_completed_successfully

volumes:
  model:
