[tool.poetry]
name = "gradwork-server"
version = "0.1.0"
description = ""
authors = ["Sergey Pavlov <self@sergeypavlov.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
starlite = "^1.51.0"
pydantic = "^1.10.4"
typer = "^0.7.0"
uvicorn = {version = "^0.20.0", extras = ["standard"]}
gunicorn = "^20.1.0"
dramatiq = {version = "^1.14.0", extras = ["rabbitmq", "watch"]}
alembic = "^1.9.2"
sqlalchemy = "^2.0.2"
psycopg2 = "^2.9.5"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.0.1"
black = "^23.1.0"
flake8 = "^6.0.0"
flake8-bugbear = "^23.1.20"
isort = "^5.12.0"
mypy = "^1.0.0"

[tool.isort]
multi_line_output = 3
profile = "black"
skip_glob = ["*/alembic/*", "*.pyx"]

[tool.mypy]
exclude = "alembic"
ignore_missing_imports = true
show_error_codes = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
